# Generated by Django 3.1.4 on 2020-12-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('user_picture', models.CharField(max_length=50)),
            ],
        ),
    ]
